### ISSUE TITLE
Proposal: expose ABCs in `backports_abc` namespace

### ISSUE THREAD

**Issue by bdarnell** [cython/backports_abc#1]
I currently use the following conditional import (in Tornado) to get the generator type for `isinstance()` checks:

```
try:
    from collections.abc import Generator as GeneratorType  # py35+
except ImportError:
    from types import GeneratorType
```

This doesn't work on py27 with `backports_abc`, since the ABCs live in `collections` instead of `collections.abc`. I need to add another attempt to the conditional (`from collections import Generator as GeneratorType`), but since the only time this import would ever succeed is when `backports_abc` is present, I'd rather just do `from backports_abc import Generator`. 

If this pattern were adopted by all users of `backports_abc`, the `patch()` function would become unnecessary (but could still be useful on py3.x, where it installs the ABCs where a backport-unaware caller would expect to find them).

Specifically, I would do something like this in `backports_abc.py` for each patchable type:

```
try:
    Generator = _collections_abc.Generator
except AttributeError:
    Generator = mk_gen()
```

**Comment by scoder** [comment]
I was actually considering to make "collections.abc" generally available as a copy of the "collections" namespace, but then "backports_abc" would still have to be imported and called by someone first.

I find this proposal a reasonable way to do it. I'll have something ready later today.

**Comment by scoder** [comment]
Done. Thanks!
https://github.com/cython/backports_abc/commit/beb52804e0ff11b0f0a7b054e292110a52339062

**Comment by bdarnell** [comment]
Thanks! FYI, the next release of Tornado will have support for coroutines that are compiled with cython (both async/await and yield-based): tornadoweb/tornado@3463036d
