### ISSUE TITLE
__subclasshook__ doesn't work for objects without __mro___ (i.e. old style classes)

### ISSUE THREAD

**Issue by RaiaN** [cython/backports_abc#7]

**Comment by robertwb** [comment]
Resolved with https://github.com/cython/backports_abc/commit/94294718c6293d1031228943590dc12fe772fa9b

**Comment by bendichter** [comment]
I'm running into this error as well. Cython 0.25.2, backports-abc 0.5, python 2.7, OSX 10.11.6. Thanks for the help and let me know if you need any more info.
